#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           5

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc config top_padding          35
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a nvim desktop='^3' follow=on
bspc rule -a zoom desktop='^5' follow=on
bspc rule -a Slack desktop='^5' follow=on
bspc rule -a Thunar desktop='^4' follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#Set the border colors for your windows for focused, active and inactive ones.
bspc config active_border_color \#136667
#bspc config normal_border_color \#8C0000
bspc config focused_border_color \#136667

#BAR_LABEL_SEPARATOR="%{T5}%{F$(xrdb -query | grep "*.color14" | cut -f 2)}%{F-}%{T-}"

xsetroot -cursor_name left_ptr &e
$HOME/.config/polybar/launch.sh &
sxhkd &
#set your wallpaper upon logging in &
feh --bg-fill ~/Downloads/wallpaper/bof3cu5hhch81.jpg & 

#Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

picom --config $HOME/.config/picom/picom.config
# If picom is running, kill it to prevent multiple instances
if ps -A | grep picom; then
	killall -q picom
fi
exec picom -b

